### ISSUE TITLE
no data displayed

### ISSUE THREAD

**Issue by Haduken731** [karrot-dev/fritzinfluxdb#25] opened 2021-08-08 06:29 UTC
I set this up with docker and infuxdb 1.8.6 (as the latest tag pulls v2 and that doesnt work, yet).
I also had to set the db initialisation tags on the influxdb container (-e INFLUXDB_DB=db -e INFLUXDB_ADMIN_USER=bla -e INFLUXDB_ADMIN_PASSWORD=blub). (temporary)
The containers seem to work, but no data is displayed in the grafana dashboard (713).

![grafik](https://user-images.githubusercontent.com/46971499/128622964-82d21084-d2c3-4c63-94fa-094c7f53a2e4.png)

![grafik](https://user-images.githubusercontent.com/46971499/128623085-0528948a-bbb4-455f-a12f-728ccd5ef7a0.png)
"0 series returned"

the fritzinfluxdb-container connects to my fritzbox, the data is posted into the db as well.
Any ideas or info i should add?

**Comment by Haduken731** [comment] 2021-08-09 13:27
as it turns out, there are errors getting the information from the fritzbox (fritzOS v7.21), specifically:
![grafik](https://user-images.githubusercontent.com/46971499/128713675-84cbbc43-459c-4dc3-ab71-0423e23dc157.png)
which seem to keep the collectd from proceeding to any other information, as the database has no measurements.

**Comment by bb-Ricardo** [comment] 2021-08-11 10:03
Hi, are you using a Cable FritzBox by any chance?

**Comment by Haduken731** [comment] 2021-08-11 11:25
Yeah I am. doesnt it work with cable ones? If not, could you point me to something working with cable ones?

**Comment by bb-Ricardo** [comment] 2021-08-13 07:22
The problem is me, lacking a cable FritzBox. I would need access and some time with a cable model to figure out the correct values. They must be there as well.

**Comment by Haduken731** [comment] 2021-08-13 08:35
Can I help you with that somehow?

**Comment by bb-Ricardo** [comment] 2021-09-02 22:17
To properly support a cable FritzBox I would need to spent some time with an actual one I have access to. Would need to extract different values and compare them to the values in the UI. 🤷‍♂️

**Comment by Baggns** [comment] 2021-09-03 05:49
For me, it looks pretty good. 
![image](https://user-images.githubusercontent.com/33479244/131956678-4bb09eee-75e8-40b0-84df-b245fa6faffb.png)

**Comment by bb-Ricardo** [comment] 2021-09-03 07:39
indeed, it looks great. 1 Gbit/s Download speed? I'm jealous 😭

**Comment by Haduken731** [comment] 2021-09-03 07:42
did you @Baggns do something different? also: i cant connect to the dashboard anymore, but thats probably a problem on my side.
but it may help if @bb-Ricardo could give a guide on how to set this up in docker only (meaning docker-compose). because thats what im aiming for. I cant seem to find any docker-compose version of a fritzbox monitor that is still working online.

**Comment by bb-Ricardo** [comment] 2021-09-03 07:45
You mean a docker compose which includes?:
* influx
* grafana
* fritzfluxdb

**Comment by Haduken731** [comment] 2021-09-03 07:46
exactly :)

**Comment by Baggns** [comment] 2021-09-03 08:10
I did nothing different and just followed the steps, but your Dashboard looks entirely different. Do you use the correct one?

**Comment by bb-Ricardo** [comment] 2022-01-04 10:56
can we close this issue?

**Comment by bb-Ricardo** [comment] 2022-03-24 20:13
Will close this issue for now

**Closed by bb-Ricardo** 2022-03-24 20:13 UTC
